services:
  # Nginx reverse proxy to handle CORS
  nginx:
    container_name: debezium-platform-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - conductor
      - stage
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]

  # PostgreSQL database for platform metadata
  postgres:
    container_name: debezium-platform-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=1"
      - "-c"
      - "max_replication_slots=1"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Debezium Platform Conductor (Backend API)
  conductor:
    container_name: debezium-platform-conductor
    image: quay.io/debezium/platform-conductor:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Quarkus datasource configuration
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      # Pipeline configuration
      - PIPELINE_OFFSET_STORAGE_CONFIG_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - PIPELINE_OFFSET_STORAGE_CONFIG_JDBC_USERNAME=user
      - PIPELINE_OFFSET_STORAGE_CONFIG_JDBC_PASSWORD=password
      - PIPELINE_SCHEMA_HISTORY_CONFIG_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - PIPELINE_SCHEMA_HISTORY_CONFIG_JDBC_USERNAME=user
      - PIPELINE_SCHEMA_HISTORY_CONFIG_JDBC_PASSWORD=password
      # CORS configuration
      - QUARKUS_HTTP_CORS=true
      - QUARKUS_HTTP_CORS_ORIGINS=/.*/
      - QUARKUS_HTTP_CORS_ACCESS_CONTROL_ALLOW_CREDENTIALS=true

  # Debezium Platform Stage (Frontend UI)
  stage:
    container_name: debezium-platform-stage
    image: quay.io/debezium/platform-stage:latest
    ports:
      - "3000:3000"
    depends_on:
      - conductor
    environment:
      - REACT_APP_API_BASE_URL=http://localhost

volumes:
  postgres_data: